import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c3c0ff",
        "surface-variant": "#dae2fd",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#dae2fd",
        "error-container": "#ffdad6",
        "surface-tint": "#4d44e3",
        "outline": "#777587",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed": "#0f0069",
        "on-secondary-container": "#00714d",
        "tertiary": "#95002b",
        "surface-dim": "#d2d9f4",
        "surface-container-lowest": "#ffffff",
        "surface": "#faf8ff",
        "on-primary-container": "#dad7ff",
        "secondary-fixed-dim": "#4edea3",
        "on-background": "#131b2e",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-container": "#bf0f3c",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "background": "#faf8ff",
        "secondary-container": "#6cf8bb",
        "on-error": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-surface": "#131b2e",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#005236",
        "secondary": "#006c49",
        "primary": "#3525cd",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed": "#ffdadb",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e2dfff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        xl: "32px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        sm: "8px",
        base: "4px",
        lg: "24px",
        "3xl": "64px",
        "2xl": "48px",
        md: "16px",
        gutter: "16px",
        "max-width": "1280px",
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out both",
        shimmer: "shimmer 2s linear infinite",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
