import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        background: "var(--color-bg)",
        "on-background": "var(--color-text)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        "surface-hover": "var(--color-surface-hover)",
        "surface-container-low": "var(--color-surface-hover)",
        "surface-container": "var(--color-surface)",
        "surface-container-high": "var(--color-surface-elevated)",
        "surface-container-highest": "var(--color-surface-elevated)",
        "surface-dim": "var(--color-bg)",
        "surface-bright": "var(--color-surface)",
        border: "var(--color-border)",
        "border-hover": "var(--color-border-hover)",
        outline: "var(--color-border)",
        "outline-variant": "var(--color-border)",
        text: "var(--color-text)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "on-surface": "var(--color-text)",
        "on-surface-variant": "var(--color-text-secondary)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-subtle": "var(--color-accent-subtle)",
        "accent-text": "var(--color-accent-text)",
        primary: "var(--color-accent)",
        "on-primary": "#1a1a1a",
        "primary-container": "var(--color-accent-subtle)",
        "on-primary-container": "var(--color-accent-text)",
        "on-primary-fixed": "#1a1a1a",
        "on-primary-fixed-variant": "#1a1a1a",
        "primary-fixed": "var(--color-accent-subtle)",
        "primary-fixed-dim": "var(--color-accent-subtle)",
        "inverse-primary": "var(--color-accent)",
        "inverse-surface": "var(--color-surface-elevated)",
        "inverse-on-surface": "var(--color-text)",
        danger: "var(--color-danger)",
        "danger-subtle": "var(--color-danger-subtle)",
        error: "var(--color-danger)",
        "on-error": "#ffffff",
        "error-container": "var(--color-danger-subtle)",
        "on-error-container": "var(--color-danger)",
        success: "var(--color-success)",
        "success-subtle": "var(--color-success-subtle)",
        secondary: "var(--color-accent)",
        "on-secondary": "#1a1a1a",
        "secondary-container": "var(--color-accent-subtle)",
        "on-secondary-container": "var(--color-accent-text)",
        "secondary-fixed": "var(--color-accent-subtle)",
        "secondary-fixed-dim": "var(--color-accent-subtle)",
        "on-secondary-fixed-variant": "var(--color-accent-text)",
        tertiary: "var(--color-danger)",
        "on-tertiary": "#ffffff",
        "tertiary-container": "var(--color-danger-subtle)",
        "tertiary-fixed": "var(--color-danger-subtle)",
        "on-tertiary-container": "var(--color-danger)",
        "surface-variant": "var(--color-surface-hover)",
        "surface-tint": "var(--color-accent)",
      },
      fontFamily: {
        display: ['"Instrument Sans"', "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-sm": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "27px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "23px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "19px", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "21px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "19px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        "4xl": "80px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        gutter: "24px",
        "max-width": "1320px",
      },
      borderRadius: {
        sm: "0.375rem",
        DEFAULT: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in": "fade-in 0.35s ease-out both",
        "fade-in-up": "fade-in-up 0.4s ease-out both",
        "scale-in": "scale-in 0.25s ease-out both",
        "slide-in-right": "slide-in-right 0.3s ease-out both",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "spin-slow": "spin-slow 3s linear infinite",
        shimmer: "shimmer 1.4s ease-in-out infinite",
        "shimmer-faster": "shimmer 0.9s ease-in-out infinite",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(8px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 8px var(--color-accent-subtle)" },
          "50%": { boxShadow: "0 0 20px var(--color-accent-subtle)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "shimmer-faster": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
